name: cautrigger-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - anndata
  - scanpy>=1.9
  - scvi-tools>=1.1
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - shap
  - pyarrow
  # notebook
  - jupyter
  - ipykernel

  - pip:
      - captum

